version: '3.9'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    container_name: django_web_server
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver2022
    ports:
      - 1433:1433
    volumes:
      - mssql_data:/var/opt/sqlserver/data
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=uzum@123KI"
volumes:
  mssql_data:
