# Generated by Django 4.1.8 on 2023-05-11 03:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_book_cover"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"permissions": [("special_status", "Can read all books")]},
        ),
    ]
